[build]
  command = "npm run build"
  publish = "dist/public"
  functions = "netlify/functions"
  
[functions]
  external_node_modules = ["@neondatabase/serverless", "ws"]
  node_bundler = "esbuild"
  
[[redirects]]
  from = "/api/dashboard/kpis"
  to = "/.netlify/functions/kpis"
  status = 200
  
[[redirects]]
  from = "/api/test"
  to = "/.netlify/functions/test"
  status = 200
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"