[build]
  command = "npm run build"
  publish = "dist/public"
  
[functions]
  external_node_modules = ["@neondatabase/serverless", "ws"]
  node_bundler = "esbuild"
  included_files = ["server/**/*", "shared/**/*"]
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-simple/:splat"
  status = 200
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"